"""remove role

Revision ID: 63b8f86ea4aa
Revises: d3fa7c5d8af2
Create Date: 2022-09-07 16:24:31.603912

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '63b8f86ea4aa'
down_revision = 'd3fa7c5d8af2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('professional', 'consumer', name='role'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
